name: Skip tests

on:
  pull_request:
    paths-ignore:
      - '**.go'
      - go.mod
      - go.sum

jobs:
  test:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.os }}
    steps:
      - run: echo 'No test required'
